# Generated by Django 6.0.4 on 2026-05-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('derived_from', 'Derived From'), ('similar_to', 'Similar To'), ('inspired_by', 'Inspired By'), ('duplicate_of', 'Duplicate Of')], default='derived_from', max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='accounts.competition')),
                ('target_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='accounts.competition')),
            ],
        ),
    ]
